apiVersion: v1
kind: Service
metadata:
  name: guestbook
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
     app.kubernetes.io/name: guestbook
  sessionAffinity: None
  type: ClusterIP
